//
//  DropStorageTable.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers

class DropStorageTable: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _creationDate: NSNumber?
    var _centerCoordinate: [NSNumber]?
    var _dropName: String?
    var _dropRadius: NSNumber?
    var _droppedContent: String?
    var _droppedMessage: String?
    var _hasBeenReceived: NSNumber?
    var _isPictureOrVideo: NSNumber?
    var _isPrivate: NSNumber?
    var _recipientUserId: String?
    
    class func dynamoDBTableName() -> String {

        return "vextitdrop-mobilehub-744279733-DropStorageTable"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_creationDate"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_creationDate" : "creationDate",
               "_centerCoordinate" : "centerCoordinate",
               "_dropName" : "dropName",
               "_dropRadius" : "dropRadius",
               "_droppedContent" : "droppedContent",
               "_droppedMessage" : "droppedMessage",
               "_hasBeenReceived" : "hasBeenReceived",
               "_isPictureOrVideo" : "isPictureOrVideo",
               "_isPrivate" : "isPrivate",
               "_recipientUserId" : "recipientUserId",
        ]
    }
}

