//
//  UsersTable.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//
/*
import Foundation
import UIKit
import AWSDynamoDB

@objcMembers

class UsersTable: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _phone: String?
    var _addressAliases: [String]?
    var _addressNames: [String]?
    var _addressPrivacyChoices: [Bool]?
    var _contacts: [String]?
    var _endpointArn: [String]?
    var _firstAddressCoordinate: [NSNumber]?
    var _name: String?
    var _secondAddressCoordinate: [NSNumber]?
    
    class func dynamoDBTableName() -> String {

        return "vextitdrop-mobilehub-744279733-UsersTable"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_phone"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_phone" : "phone",
               "_addressAliases" : "addressAliases",
               "_addressPrivacyChoices" : "addressPrivacyChoices",
               "_contacts" : "contacts",
               "_endpointArn" : "endpointArn",
               "_firstAddressCoordinate" : "firstAddressCoordinate",
               "_name" : "name",
               "_secondAddressCoordinate" : "secondAddressCoordinate",
        ]
    }
 }*/

